### ISSUE TITLE
追随

### ISSUE THREAD

**Issue by amiacoder** [iosdeveloperpanc/GodEYE#3]

**Comment by iosdeveloperpanc** [comment]
岳大屌是谁。。。黑人问号...

**Comment by devtofu** [comment]
你 cosplay 的这个。

**Comment by iosdeveloperpanc** [comment]
一朋友说实现天眼查APP中的查关系界面有难度，于是我就玩了一下APP，花了周末的2天时间就写了一下，后来为了实现一对多的关系又重构了几次代码，觉得还行，就发上了。并不知道所谓的岳大屌是何许人也~
